models:
  - name: int__smartphones_brands
    description: "Справочник наименований брендов смартфонов"
    columns:
    - name: brand_name
      description: "Наименование бренда смартфона"
      tests:
        - unique
        - not_null

  - name: int__smartphones_combination
    description: "Таблица комбинаций22222 характеристик процессоров и аккумуляторов"
    columns:
    - name: processor_brand
      description: "Наименование бренда процессора"
    - name: num_cores
      description: "Количество ядер процессора"
    - name: processor_speed
      description: "Скорость процессора"
    - name: battery_capacity
      description: "Емкость аккумулятора"
    - name: combination_count
      description: "Количество совпадений комбинаций характеристик процессоров и аккумуляторов"